var annotated_dup =
[
    [ "VoxelToolkit", "namespace_voxel_toolkit.html", [
      [ "BooleanArray", "struct_voxel_toolkit_1_1_boolean_array.html", null ],
      [ "CopyVerticesJob", "struct_voxel_toolkit_1_1_copy_vertices_job.html", null ],
      [ "DynamicVoxelObject", "class_voxel_toolkit_1_1_dynamic_voxel_object.html", "class_voxel_toolkit_1_1_dynamic_voxel_object" ],
      [ "DynamicVoxelObjectModelLoader", "class_voxel_toolkit_1_1_dynamic_voxel_object_model_loader.html", null ],
      [ "Face", "struct_voxel_toolkit_1_1_face.html", null ],
      [ "FacesGenerationJob", "struct_voxel_toolkit_1_1_faces_generation_job.html", null ],
      [ "Group", "class_voxel_toolkit_1_1_group.html", "class_voxel_toolkit_1_1_group" ],
      [ "HierarchyNode", "class_voxel_toolkit_1_1_hierarchy_node.html", "class_voxel_toolkit_1_1_hierarchy_node" ],
      [ "IndexGenerator", "class_voxel_toolkit_1_1_index_generator.html", null ],
      [ "IVoxelObjectPartReleaseHandler", "interface_voxel_toolkit_1_1_i_voxel_object_part_release_handler.html", "interface_voxel_toolkit_1_1_i_voxel_object_part_release_handler" ],
      [ "IVoxelObjectPartSetupHandler", "interface_voxel_toolkit_1_1_i_voxel_object_part_setup_handler.html", "interface_voxel_toolkit_1_1_i_voxel_object_part_setup_handler" ],
      [ "Layer", "class_voxel_toolkit_1_1_layer.html", "class_voxel_toolkit_1_1_layer" ],
      [ "MagicaVoxelImporter", "class_voxel_toolkit_1_1_magica_voxel_importer.html", null ],
      [ "Material", "struct_voxel_toolkit_1_1_material.html", "struct_voxel_toolkit_1_1_material" ],
      [ "MaterialParameters", "struct_voxel_toolkit_1_1_material_parameters.html", null ],
      [ "Matrix3x3Int", "struct_voxel_toolkit_1_1_matrix3x3_int.html", null ],
      [ "MeshDescriptor", "struct_voxel_toolkit_1_1_mesh_descriptor.html", "struct_voxel_toolkit_1_1_mesh_descriptor" ],
      [ "MeshGenerationJob", "struct_voxel_toolkit_1_1_mesh_generation_job.html", null ],
      [ "Model", "class_voxel_toolkit_1_1_model.html", "class_voxel_toolkit_1_1_model" ],
      [ "ModifyObjectInRuntimeDemo", "class_voxel_toolkit_1_1_modify_object_in_runtime_demo.html", null ],
      [ "PartInfo", "struct_voxel_toolkit_1_1_part_info.html", "struct_voxel_toolkit_1_1_part_info" ],
      [ "Quad", "struct_voxel_toolkit_1_1_quad.html", null ],
      [ "QuadGenerationJob", "struct_voxel_toolkit_1_1_quad_generation_job.html", null ],
      [ "Reader", "class_voxel_toolkit_1_1_reader.html", null ],
      [ "ReadonlyArray", "struct_voxel_toolkit_1_1_readonly_array.html", null ],
      [ "Shape", "class_voxel_toolkit_1_1_shape.html", "class_voxel_toolkit_1_1_shape" ],
      [ "Transformation", "class_voxel_toolkit_1_1_transformation.html", "class_voxel_toolkit_1_1_transformation" ],
      [ "TransformationFrame", "struct_voxel_toolkit_1_1_transformation_frame.html", "struct_voxel_toolkit_1_1_transformation_frame" ],
      [ "TransformedMaterial", "struct_voxel_toolkit_1_1_transformed_material.html", null ],
      [ "Vertex", "struct_voxel_toolkit_1_1_vertex.html", null ],
      [ "VertexGenerationJob", "struct_voxel_toolkit_1_1_vertex_generation_job.html", null ],
      [ "Voxel", "struct_voxel_toolkit_1_1_voxel.html", "struct_voxel_toolkit_1_1_voxel" ],
      [ "VoxelAsset", "class_voxel_toolkit_1_1_voxel_asset.html", "class_voxel_toolkit_1_1_voxel_asset" ],
      [ "VoxelData", "struct_voxel_toolkit_1_1_voxel_data.html", "struct_voxel_toolkit_1_1_voxel_data" ],
      [ "VoxelFileReadException", "class_voxel_toolkit_1_1_voxel_file_read_exception.html", null ],
      [ "VoxelImporter", "class_voxel_toolkit_1_1_voxel_importer.html", null ],
      [ "VoxelObject", "class_voxel_toolkit_1_1_voxel_object.html", "class_voxel_toolkit_1_1_voxel_object" ]
    ] ]
];