var annotated_dup =
[
    [ "VoxelToolkit", "namespace_voxel_toolkit.html", [
      [ "Demo", "namespace_voxel_toolkit_1_1_demo.html", [
        [ "ExplodeVoxelDemoParticles", "class_voxel_toolkit_1_1_demo_1_1_explode_voxel_demo_particles.html", null ],
        [ "ExplodeVoxelDemoRigidBodies", "class_voxel_toolkit_1_1_demo_1_1_explode_voxel_demo_rigid_bodies.html", null ],
        [ "Loader", "class_voxel_toolkit_1_1_demo_1_1_loader.html", null ],
        [ "ModifyObjectInRuntimeDemo", "class_voxel_toolkit_1_1_demo_1_1_modify_object_in_runtime_demo.html", null ],
        [ "RaycastObjectDemo", "class_voxel_toolkit_1_1_demo_1_1_raycast_object_demo.html", null ]
      ] ],
      [ "Editor", "namespace_voxel_toolkit_1_1_editor.html", [
        [ "GeneratorListPropertyDrawer", "class_voxel_toolkit_1_1_editor_1_1_generator_list_property_drawer.html", null ],
        [ "GenericListPropertyDrawer", "class_voxel_toolkit_1_1_editor_1_1_generic_list_property_drawer.html", null ],
        [ "MagicaVoxelImporter", "class_voxel_toolkit_1_1_editor_1_1_magica_voxel_importer.html", null ],
        [ "ObjectGeneratorsList", "class_voxel_toolkit_1_1_editor_1_1_object_generators_list.html", null ],
        [ "VoxelImporter", "class_voxel_toolkit_1_1_editor_1_1_voxel_importer.html", null ]
      ] ],
      [ "MagicaVoxel", "namespace_voxel_toolkit_1_1_magica_voxel.html", [
        [ "GroupElement", "class_voxel_toolkit_1_1_magica_voxel_1_1_group_element.html", null ],
        [ "HierarchyElement", "class_voxel_toolkit_1_1_magica_voxel_1_1_hierarchy_element.html", null ],
        [ "ModelReference", "class_voxel_toolkit_1_1_magica_voxel_1_1_model_reference.html", null ],
        [ "ShapeElement", "class_voxel_toolkit_1_1_magica_voxel_1_1_shape_element.html", null ],
        [ "TransformElement", "class_voxel_toolkit_1_1_magica_voxel_1_1_transform_element.html", null ]
      ] ],
      [ "BooleanArray", "struct_voxel_toolkit_1_1_boolean_array.html", null ],
      [ "Color32", "struct_voxel_toolkit_1_1_color32.html", null ],
      [ "CopyVerticesJob", "struct_voxel_toolkit_1_1_copy_vertices_job.html", null ],
      [ "CountQuadsJob", "struct_voxel_toolkit_1_1_count_quads_job.html", null ],
      [ "DynamicVoxelObject", "class_voxel_toolkit_1_1_dynamic_voxel_object.html", "class_voxel_toolkit_1_1_dynamic_voxel_object" ],
      [ "DynamicVoxelObjectModelLoader", "class_voxel_toolkit_1_1_dynamic_voxel_object_model_loader.html", null ],
      [ "Face", "struct_voxel_toolkit_1_1_face.html", null ],
      [ "FacesGenerationJob", "struct_voxel_toolkit_1_1_faces_generation_job.html", null ],
      [ "GameObjectBuilder", "class_voxel_toolkit_1_1_game_object_builder.html", "class_voxel_toolkit_1_1_game_object_builder" ],
      [ "Group", "class_voxel_toolkit_1_1_group.html", "class_voxel_toolkit_1_1_group" ],
      [ "HierarchyNode", "class_voxel_toolkit_1_1_hierarchy_node.html", "class_voxel_toolkit_1_1_hierarchy_node" ],
      [ "IndexGenerator", "class_voxel_toolkit_1_1_index_generator.html", null ],
      [ "IVoxelObjectPartReleaseHandler", "interface_voxel_toolkit_1_1_i_voxel_object_part_release_handler.html", "interface_voxel_toolkit_1_1_i_voxel_object_part_release_handler" ],
      [ "IVoxelObjectPartSetupHandler", "interface_voxel_toolkit_1_1_i_voxel_object_part_setup_handler.html", "interface_voxel_toolkit_1_1_i_voxel_object_part_setup_handler" ],
      [ "Layer", "class_voxel_toolkit_1_1_layer.html", "class_voxel_toolkit_1_1_layer" ],
      [ "MagicaVoxelImporter", "class_voxel_toolkit_1_1_magica_voxel_importer.html", "class_voxel_toolkit_1_1_magica_voxel_importer" ],
      [ "Material", "struct_voxel_toolkit_1_1_material.html", "struct_voxel_toolkit_1_1_material" ],
      [ "MaterialParameters", "struct_voxel_toolkit_1_1_material_parameters.html", null ],
      [ "Matrix3x3Int", "struct_voxel_toolkit_1_1_matrix3x3_int.html", "struct_voxel_toolkit_1_1_matrix3x3_int" ],
      [ "MeshColliderSetupHandler", "class_voxel_toolkit_1_1_mesh_collider_setup_handler.html", "class_voxel_toolkit_1_1_mesh_collider_setup_handler" ],
      [ "MeshDescriptor", "struct_voxel_toolkit_1_1_mesh_descriptor.html", "struct_voxel_toolkit_1_1_mesh_descriptor" ],
      [ "MeshGenerationJob", "struct_voxel_toolkit_1_1_mesh_generation_job.html", null ],
      [ "Model", "class_voxel_toolkit_1_1_model.html", "class_voxel_toolkit_1_1_model" ],
      [ "PartInfo", "struct_voxel_toolkit_1_1_part_info.html", "struct_voxel_toolkit_1_1_part_info" ],
      [ "Quad", "struct_voxel_toolkit_1_1_quad.html", null ],
      [ "QuadGenerationJob", "struct_voxel_toolkit_1_1_quad_generation_job.html", null ],
      [ "RaycastHit", "struct_voxel_toolkit_1_1_raycast_hit.html", "struct_voxel_toolkit_1_1_raycast_hit" ],
      [ "Reader", "class_voxel_toolkit_1_1_reader.html", null ],
      [ "ReadonlyArray", "struct_voxel_toolkit_1_1_readonly_array.html", null ],
      [ "Shape", "class_voxel_toolkit_1_1_shape.html", "class_voxel_toolkit_1_1_shape" ],
      [ "SnowVoxelObjectModifier", "class_voxel_toolkit_1_1_snow_voxel_object_modifier.html", null ],
      [ "TextureDescriptor", "struct_voxel_toolkit_1_1_texture_descriptor.html", null ],
      [ "TextureFillJob", "struct_voxel_toolkit_1_1_texture_fill_job.html", null ],
      [ "Transformation", "class_voxel_toolkit_1_1_transformation.html", "class_voxel_toolkit_1_1_transformation" ],
      [ "TransformationFrame", "struct_voxel_toolkit_1_1_transformation_frame.html", "struct_voxel_toolkit_1_1_transformation_frame" ],
      [ "TransformedMaterial", "struct_voxel_toolkit_1_1_transformed_material.html", null ],
      [ "Vertex", "struct_voxel_toolkit_1_1_vertex.html", null ],
      [ "VertexGenerationJob", "struct_voxel_toolkit_1_1_vertex_generation_job.html", null ],
      [ "Voxel", "struct_voxel_toolkit_1_1_voxel.html", "struct_voxel_toolkit_1_1_voxel" ],
      [ "VoxelAsset", "class_voxel_toolkit_1_1_voxel_asset.html", "class_voxel_toolkit_1_1_voxel_asset" ],
      [ "VoxelData", "struct_voxel_toolkit_1_1_voxel_data.html", "struct_voxel_toolkit_1_1_voxel_data" ],
      [ "VoxelDataReadException", "class_voxel_toolkit_1_1_voxel_data_read_exception.html", null ],
      [ "VoxelImporter", "class_voxel_toolkit_1_1_voxel_importer.html", null ],
      [ "VoxelObject", "class_voxel_toolkit_1_1_voxel_object.html", "class_voxel_toolkit_1_1_voxel_object" ],
      [ "VoxelObjectModifier", "class_voxel_toolkit_1_1_voxel_object_modifier.html", null ],
      [ "VoxelQueryResult", "struct_voxel_toolkit_1_1_voxel_query_result.html", null ]
    ] ],
    [ "GenericList", "class_generic_list.html", null ],
    [ "IVoxelObjectPreprocessor", "interface_i_voxel_object_preprocessor.html", null ]
];